<SingupScreenView>
    MDFloatLayout:
        orientation: "horizontal"
        md_bg_color:74/255,20/255,140/255,1

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            pos_hint:{"center_x": .25, "center_y": .5}
            size_hint_x:0.5

            Image:
                source: "assets/images/hands.png"
                pos_hint:{"center_x":.5, "center_y":.5}
                size_hint: None, None
                height: 250
                width:  250
                canvas.before:
                    Color:
                        rgba:1,1,1,1
                    Ellipse:
                        size:290,290
                        pos:52,180

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            pos_hint:{"center_x": .75, "center_y": .5}
            size_hint_x:0.5
            MDLabel:
                id: login_label
                text: "REGISTRAR NUEVO USUARIO"
                font_style: "H4"
                adaptive_height: True
                halign: "center"

            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                padding: "50dp"
                spacing: "20dp"
                MDTextField:
                    id:fullname
                    hint_text: "Nombres y Apellidos"
                    icon_left: "account"
                    mode:"round"
                    required: True
                    on_text: root.controller.set_user_data("fullname", self.text)
                MDTextField:
                    id:phone
                    hint_text: "Telefono"
                    icon_left: "phone"
                    mode:"round"
                    required: True
                    on_text: root.controller.set_user_data("phone", self.text)
                MDTextField:
                    id:email
                    hint_text: "Correo Electrónico"
                    icon_left: "email"
                    mode:"round"
                    required: True
                    validator: "email"
                    helper_text_mode:"on_error"
                    on_text: root.controller.set_user_data("email", self.text)
                MDTextField:
                    id:pssword
                    hint_text: "Contraseña"
                    icon_left: "key-variant"
                    mode:"round"
                    password:True
                    required: True
                    on_text: root.controller.set_user_data("password", root.controller.encrypt_password(self.text))
                    on_text: root.controller.set_password_data("password", self.text)
                MDTextField:
                    id:confirm
                    hint_text: "Confirmar Contraseña"
                    icon_left: "key-variant"
                    mode:"round"
                    password:True
                    required: True
                    on_text: root.controller.set_password_data("confirm", self.text)
                    on_text_validate:root.controller.confirm_password_data()
                MDFillRoundFlatButton:
                    text: "                        REGISTRAR                         "
                    md_bg_color:"green"
                    on_release:
                        root.controller.set_user_data("created_ad",root.date)
                        root.controller.set_user_data("last_login",root.date)
                        root.controller.set_user_data("idRol",0)
                        root.controller.set_user_data("idElections",0)
                        root.controller.on_tap_button_signup()
                    pos_hint: {"center_x": .5, "center_y": .1}

        MDLabel:
            id:message
            pos_hint: {"center_x": .5, "center_y": .8}
            color:[.95,0,0,1]
            font_style:"H6"
        MDTextButton:
            id: go_login
            text: "Ya tienes cuenta?. inicia sesión aqui"
            pos_hint: {"center_x": .5, "center_y": .12}
            on_press:
                root.controller.on_tap_button_go_login("login screen")